USE [master]
GO

/****** Object:  Database [ProjectOrganizer]    Script Date: 6/13/2017 3:45:55 PM ******/
CREATE DATABASE [ProjectOrganizer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectOrganizer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ProjectOrganizer.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjectOrganizer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ProjectOrganizer_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ProjectOrganizer] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectOrganizer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectOrganizer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectOrganizer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectOrganizer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectOrganizer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectOrganizer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProjectOrganizer] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectOrganizer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectOrganizer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectOrganizer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectOrganizer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProjectOrganizer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjectOrganizer] SET QUERY_STORE = OFF
GO

USE [ProjectOrganizer]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ProjectOrganizer] SET  READ_WRITE 
GO

